// Comprehensive list of disposable/temporary email domains
const TEMP_EMAIL_DOMAINS: string[] = [
  // Major disposable email services
  "tempmail.com", "temp-mail.org", "temp-mail.io", "tempail.com",
  "guerrillamail.com", "guerrillamail.info", "guerrillamail.net", "guerrillamail.org", "guerrillamail.de",
  "guerrilla.mltr.me", "grr.la", "guerrillamailblock.com",
  "mailinator.com", "mailinator.net", "mailinator2.com",
  "maildrop.cc", "maildrop.ml",
  "yopmail.com", "yopmail.fr", "yopmail.net", "yopmail.gq",
  "10minutemail.com", "10minutemail.net", "10minutemail.org",
  "10minutemail.co.za", "10minute-mail.com",
  "throwaway.email", "throwawaymail.com",
  "trashmail.com", "trashmail.me", "trashmail.net", "trashmail.org", "trashmail.io",
  "sharklasers.com", "guerrillamailblock.com",
  "dispostable.com",
  "fakeinbox.com", "fakemail.net",
  "mailnesia.com",
  "tempr.email",
  "discard.email",
  "discardmail.com", "discardmail.de",
  "mohmal.com",
  "getnada.com", "nada.email", "nada.ltd",
  "emailondeck.com",
  "33mail.com",
  "maildax.com",
  "getairmail.com",
  "filzmail.com",
  "inboxbear.com",
  "mailcatch.com",
  "mailexpire.com",
  "mailmoat.com",
  "mailnull.com",
  "mailscrap.com",
  "mailshell.com",
  "mailsiphon.com",
  "mailslurp.com",
  "mailtemp.net",
  "mailzilla.com",
  "mintemail.com",
  "moakt.com",
  "mytemp.email",
  "mytrashmail.com",
  "nobulk.com",
  "nospamfor.us",
  "nowmymail.com",
  "objectmail.com",
  "obobbo.com",
  "onewaymail.com",
  "spambox.us",
  "spamcowboy.com",
  "spameveryonecom", 
  "spamfree24.org",
  "spamgourmet.com",
  "spamhole.com",
  "spamify.com",
  "spaml.com",
  "spamspot.com",
  "tempinbox.com",
  "tempomail.fr",
  "temporaryemail.net",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymailaddress.com",
  "tmpmail.net", "tmpmail.org",
  "trash-mail.at", "trash-mail.com",
  "trashymail.com", "trashymail.net",
  "trbvm.com",
  "uggsrock.com",
  "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
  "wh4f.org",
  "willselfdestruct.com",
  "yep.it",
  "yogamaven.com",
  "zehnminutenmail.de",
  "zoemail.org",
  "zetmail.com",
  "mailnator.com",
  "binkmail.com",
  "bobmail.info",
  "chammy.info",
  "devnullmail.com",
  "dfgh.net",
  "digitalsanctuary.com",
  "emailigo.de",
  "emailisvalid.com",
  "emailthe.net",
  "emailtmp.com",
  "emailwarden.com",
  "emailx.at.hm",
  "emailz.cf", "emailz.ga", "emailz.gq", "emailz.ml",
  "emz.net",
  "enterto.com",
  "ephemail.net",
  "etranquil.com", "etranquil.net", "etranquil.org",
  "evopo.com",
  "explodemail.com",
  "eyepaste.com",
  "fastacura.com",
  "filzmail.com",
  "fixmail.tk",
  "flyspam.com",
  "fr33mail.info",
  "frapmail.com",
  "front14.org",
  "fux0ringduh.com",
  "gelitik.in",
  "ghosttexter.de",
  "girlsundertheinfluence.com",
  "gishpuppy.com",
  "great-host.in",
  "greensloth.com",
  "haltospam.com",
  "harakirimail.com",
  "hidemail.de",
  "hidzz.com",
  "hotpop.com",
  "ieatspam.eu", "ieatspam.info",
  "imails.info",
  "inboxalias.com",
  "inboxclean.com", "inboxclean.org",
  "incognitomail.com", "incognitomail.net", "incognitomail.org",
  "insorg-mail.info",
  "ipoo.org",
  "irish2me.com",
  "jetable.com", "jetable.fr.nf", "jetable.net", "jetable.org",
  "jnxjn.com",
  "jourrapide.com",
  "kasmail.com",
  "kaspop.com",
  "keepmymail.com",
  "killmail.com", "killmail.net",
  "klzlk.com",
  "koszmail.pl",
  "kurzepost.de",
  "lawlita.com",
  "letthemeatspam.com",
  "lhsdv.com",
  "lifebyfood.com",
  "link2mail.net",
  "litedrop.com",
  "lol.ovpn.to",
  "lookugly.com",
  "lopl.co.cc",
  "lortemail.dk",
  "lr78.com",
  "m4ilweb.info",
  "maboard.com",
  "mail-temporaire.fr",
  "mail.by",
  "mail.mezimages.net",
  "mail2rss.org",
  "mail333.com",
  "mail4trash.com",
  "mailbidon.com",
  "mailblocks.com",
  "mailcatch.com",
  "maileater.com",
  "mailexpire.com",
  "mailforspam.com",
  "mailfree.ga", "mailfree.gq", "mailfree.ml",
  "mailfreeonline.com",
  "mailguard.me",
  "mailhazard.com", "mailhazard.us",
  "mailhz.me",
  "mailimate.com",
  "mailin8r.com",
  "mailinater.com",
  "mailincubator.com",
  "mailismagic.com",
  "mailmate.com",
  "mailme.ir", "mailme.lv",
  "mailmetrash.com",
  "mailnull.com",
  "mailorg.org",
  "mailpick.biz",
  "mailrock.biz",
  "mailscrap.com",
  "mailseal.de",
  "mailshell.com",
  "mailsiphon.com",
  "mailslite.com",
  "mailtemp.info",
  "mailtothis.com",
  "mailtrash.net",
  "mailzilla.com", "mailzilla.org",
  "mbx.cc",
  "mega.zik.dj",
  "meltmail.com",
  "messagebeamer.de",
  "mezimages.net",
  "mfsa.ru",
  "mierdamail.com",
  "migmail.pl",
  "mmmmail.com",
  "mobi.web.id",
  "mobileninja.co.uk",
  "moncourrier.fr.nf",
  "monemail.fr.nf",
  "monmail.fr.nf",
  "mt2015.com",
  "mx0.wwwnew.eu",
  "mypartyclip.de",
  "myphantom.com",
  "mysamp.de",
  "myspaceinc.com", "myspaceinc.net", "myspaceinc.org",
  "myspacepimpedup.com",
  "mytemps.com",
  "mytrashmail.com",
  "nabala.com",
  "neomailbox.com",
  "nepwk.com",
  "nervmich.net",
  "nervtansen.de",
  "netmails.com", "netmails.net",
  "neverbox.com",
  "no-spam.ws",
  "noblepioneer.com",
  "nobulk.com",
  "noclickemail.com",
  "nogmailspam.info",
  "nomail.xl.cx",
  "nomail2me.com",
  "nomorespamemails.com",
  "nonspam.eu",
  "nonspammer.de",
  "noref.in",
  "nospam.ze.tc",
  "nospam4.us",
  "nospamfor.us",
  "nospammail.net",
  "nospamthanks.info",
  "nothingtoseehere.ca",
  "nowmymail.com",
  "nurfuerspam.de",
  "nus.edu.sg",
  "nwldx.com",
  "objectmail.com",
  "obobbo.com",
  "odnorazovoe.ru",
  "oneoffemail.com",
  "onewaymail.com",
  "oopi.org",
  "ordinaryamerican.net",
  "otherinbox.com",
  "ourklips.com",
  "outlawspam.com",
  "ovpn.to",
  "owlpic.com",
  "pancakemail.com",
  "pjjkp.com",
  "plexolan.de",
  "pookmail.com",
  "privacy.net",
  "proxymail.eu",
  "prtnx.com",
  "putthisinyourspamdatabase.com",
  "qq.com",
  "quickinbox.com",
  "rcpt.at",
  "reallymymail.com",
  "recode.me",
  "recursor.net",
  "regbypass.com", "regbypass.comsafe-mail.net",
  "rejectmail.com",
  "reliable-mail.com",
  "rhyta.com",
  "rklips.com",
  "rmqkr.net",
  "royal.net",
  "rppkn.com",
  "rtrtr.com",
  "s0ny.net",
  "safe-mail.net",
  "safersignup.de",
  "safetymail.info",
  "safetypost.de",
  "sandelf.de",
  "saynotospams.com",
  "scatmail.com",
  "schafmail.de",
  "selfdestructingmail.com",
  "sendspamhere.com",
  "shiftmail.com",
  "shitmail.me", "shitmail.org",
  "shortmail.net",
  "sibmail.com",
  "skeefmail.com",
  "slaskpost.se",
  "slipry.net",
  "slopsbox.com",
  "slowslow.de",
  "smashmail.de",
  "smellfear.com",
  "snakemail.com",
  "sneakemail.com",
  "sneakymail.de",
  "snkmail.com",
  "sofimail.com",
  "sofort-mail.de",
  "softpls.asia",
  "sogetthis.com",
  "solvemail.info",
  "soodonims.com",
  "spam.la", "spam.su",
  "spam4.me",
  "spamavert.com",
  "spambob.com", "spambob.net", "spambob.org",
  "spambog.com", "spambog.de", "spambog.ru",
  "spambox.info", "spambox.irishspringrealty.com", "spambox.us",
  "spamcannon.com", "spamcannon.net",
  "spamcero.com",
  "spamcon.org",
  "spamcorptastic.com",
  "spamcowboy.com", "spamcowboy.net", "spamcowboy.org",
  "spamday.com",
  "spamex.com",
  "spamfighter.cf", "spamfighter.ga", "spamfighter.gq", "spamfighter.ml", "spamfighter.tk",
  "spamfree.eu", "spamfree24.com", "spamfree24.de", "spamfree24.eu",
  "spamfree24.info", "spamfree24.net", "spamfree24.org",
  "spamgoes.in",
  "spamherelots.com",
  "spamhereplease.com",
  "spamhole.com",
  "spamify.com",
  "spaminator.de",
  "spamkill.info",
  "spaml.com", "spaml.de",
  "spammotel.com",
  "spamobox.com",
  "spamoff.de",
  "spamslicer.com",
  "spamspot.com",
  "spamstack.net",
  "spamthis.co.uk",
  "spamtrail.com",
  "spamtrap.ro",
  "speed.1s.fr",
  "supergreatmail.com",
  "supermailer.jp",
  "suremail.info",
  "svk.jp",
  "sweetxxx.de",
  "tafmail.com",
  "tagyoureit.com",
  "talkinator.com",
  "tapchicuoihoi.com",
  "teewars.org",
  "teleworm.com", "teleworm.us",
  "temp.emeraldcraft.com", "temp.headstrong.de",
  "tempalias.com",
  "tempe4mail.com",
  "tempemail.co.za", "tempemail.com", "tempemail.net", "tempemail.biz",
  "tempinbox.co.uk", "tempinbox.com",
  "tempmail.eu", "tempmail.it", "tempmail.us",
  "tempmail2.com",
  "tempmaildemo.com",
  "tempmailer.com", "tempmailer.de",
  "tempmailid.com",
  "tempomail.fr",
  "temporarily.de",
  "temporarioemail.com.br",
  "temporaryemail.net", "temporaryemail.us",
  "temporaryforwarding.com",
  "temporaryinbox.com",
  "temporarymailaddress.com",
  "thanksnospam.info",
  "thankyou2010.com",
  "thc.st",
  "thecriminals.com",
  "thisisnotmyrealemail.com",
  "throam.com",
  "throwawayemailaddress.com",
  "tittbit.in",
  "tmail.ws",
  "tmailinator.com",
  "toiea.com",
  "toomail.biz",
  "tradermail.info",
  "trash2009.com", "trash2010.com", "trash2011.com",
  "trash-amil.com", "trash-mail.at", "trash-mail.cf",
  "trash-mail.com", "trash-mail.de", "trash-mail.ga",
  "trash-mail.gq", "trash-mail.ml", "trash-mail.tk",
  "trashdevil.com", "trashdevil.de",
  "trashemail.de",
  "trashmail.at",
  "trashmail.com", "trashmail.de", "trashmail.io",
  "trashmail.me", "trashmail.net", "trashmail.org",
  "trashmail.ws",
  "trashmailer.com",
  "trashymail.com", "trashymail.net",
  "turual.com",
  "twinmail.de",
  "tyldd.com",
  "uggsrock.com",
  "upliftnow.com",
  "uplipht.com",
  "venompen.com",
  "veryreallvemail.com",
  "viditag.com",
  "viewcastmedia.com", "viewcastmedia.net", "viewcastmedia.org",
  "vomoto.com",
  "vpn.st",
  "vsimcard.com",
  "vubby.com",
  "wasteland.rfc822.org",
  "webemail.me",
  "weg-werf-email.de",
  "wegwerf-emails.de",
  "wegwerfadresse.de",
  "wegwerfemail.com", "wegwerfemail.de",
  "wegwerfmail.de", "wegwerfmail.info", "wegwerfmail.net", "wegwerfmail.org",
  "wilemail.com",
  "willhackforfood.biz",
  "willselfdestruct.com",
  "winemaven.info",
  "wronghead.com",
  "wuzup.net", "wuzupmail.net",
  "wwwnew.eu",
  "xagloo.com",
  "xemaps.com",
  "xents.com",
  "xjoi.com",
  "xmaily.com",
  "xoxy.net",
  "yep.it",
  "yogamaven.com",
  "yopmail.com", "yopmail.fr", "yopmail.gq", "yopmail.net",
  "yuurok.com",
  "zehnminuten.de",
  "zehnminutenmail.de",
  "zippymail.info",
  "zoaxe.com",
  "zoemail.org",
];

// Create a Set for O(1) lookups
const TEMP_DOMAINS_SET = new Set(TEMP_EMAIL_DOMAINS.map(d => d.toLowerCase()));

/**
 * Checks if an email address uses a known disposable/temporary email provider.
 * Returns true if the email is from a temp provider (should be blocked).
 */
export function isTempEmail(email: string): boolean {
  if (!email || !email.includes("@")) return false;
  const domain = email.split("@")[1]?.toLowerCase();
  if (!domain) return false;
  return TEMP_DOMAINS_SET.has(domain);
}
