project_id = "tiupdhnjdcmgbqifwkrd"

[functions.flowpay-pix]
verify_jwt = false

[functions.admin-analytics]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false

[functions.utmify-event]
verify_jwt = false

[functions.meta-capi]
verify_jwt = false

[functions.flowpay-card]
verify_jwt = false

[functions.admin-post-payment]
verify_jwt = false

[functions.restore-orders-json]
verify_jwt = false

[functions.admin-data]
verify_jwt = false

[functions.firestore-diagnostic]
verify_jwt = false

[functions.upload-r2]
verify_jwt = false

[functions.restore-orders]
verify_jwt = false

[functions.restore-products]
verify_jwt = false
