project_id = "tiupdhnjdcmgbqifwkrd"

[functions.flowpay-pix]
verify_jwt = false

[functions.utmify-track]
verify_jwt = false

[functions.admin-analytics]
verify_jwt = false

[functions.track-analytics]
verify_jwt = false
